name: TinyAlert
author: danillos 
category: Interface
tags: [animation, message, alert]
docs: http://github.com/danillos/tinyalert/blob/master/Docs/TinyAlert.md
demo: http://www.danillocesar.com.br/labs/tinyalert
#current: 0.5